### ISSUE TITLE
Why there are 15 MPIIGaze trained models?

### ISSUE THREAD

**Issue by nicola-scarano** [Ahmednull/L2CS-Net#11]
First of all thanks Ahmed for the work. Here the question:

Why there are 15 MPIIGaze trained models and not just one as with the Gaze360 Dataset? And in this case how should the inference be performed?

**Comment by Ahmednull** [comment]
Since we use k-fold cross validation for MPIIFaceGaze dataset with k=15.

**Comment by hefei12** [comment]
> 首先感谢艾哈迈德的工作。这里有一个问题：
> 
> 为什么有 15 个 MPIIGaze 训练的模型，而不是像 Gaze360 数据集那样只有一个？在这种情况下，应该如何进行推理？

Hello, can you guide me on how to reason?

**Comment by Ahmednull** [comment]
We use 15-fold cross-validation to evaluate L2CS-Net on the MPIIFaceGaze dataset. The model is trained on data from all 15 subjects except one, which is held as the test set. This procedure is repeated in such a way that each subject is used as a test subject once, ensuring that the evaluation covers the variability between different individuals in a comprehensive way. so we have 15 models

**Comment by Ahmednull** [comment]
We use 15-fold cross-validation to evaluate L2CS-Net on the MPIIFaceGaze dataset. The model is trained on data from all 15 subjects except one, which is held as the test set. This procedure is repeated in such a way that each subject is used as a test subject once, ensuring that the evaluation covers the variability between different individuals in a comprehensive way. so we have 15 models
