### ISSUE TITLE
Pose of the faces?

### ISSUE THREAD

**Issue by hammerchu** [Ahmednull/L2CS-Net#16]
Thanks for the code~ 

I am trying to find the position where the gaze vector intercept with a vertical 2D plan in the camera space, therefore I want to know the coords of faces in the camera space, I am wondering if the network already predicted the pose of the faces? If yes is that a way that I can extract it instead of running my own head pose estimation?

**Comment by Ahmednull** [comment]
Our network only predicts the gaze direction in spherical coordinates (pitch and yaw). If you need head pose, you should use another network.
