### ISSUE TITLE
Hi. Urgent

### ISSUE THREAD

**Issue by sanslicoin** [Ahmednull/L2CS-Net#19]
Hi Ahmednull; Apply data preprocessing from here. The link is not working. Would you be interested please. Or how can you provide a different link on the related data preprocessing method? please take care

**Comment by beji02** [comment]
I have the same issue. Can you help?

**Comment by Ahmednull** [comment]
The link appears to be functioning smoothly most of the time, but it not working occasionaly. I recommend trying to access it at different times.
