### ISSUE TITLE
question for expectation 

### ISSUE THREAD

**Issue by Nico-Rain** [Ahmednull/L2CS-Net#3]
thanks for your great job.
i have a question, could you explain the process of calculating the expectation of the probability distribution?

What do these codes mean?
`pitch_predicted = \
                        torch.sum(pitch_predicted * idx_tensor, 1) * 3 - 42     
 yaw_predicted = \
                        torch.sum(yaw_predicted * idx_tensor, 1) * 3 - 42`

**Comment by Ahmednull** [comment]
Hi,

The expected value is calculated by multiplying each of the possible outcomes by the probability each outcome will occur and then summing all of those values and this is the explanation of the first part of the equation:

**Comment by Ahmednull** [comment]
Hi,

1- The expected value is calculated by multiplying each of the possible outcomes by the probability each outcome will occur and then summing all of those values and this is the explanation of the first part of the equation:
        torch.sum(pitch_predicted * idx_tensor, 1) 

2- The second part of the equation is to convert the expected bin value back to the gaze angle in the normal range
           i.e # mapping  bins from (0 to 27) to angels (-42 to 42)
