### ISSUE TITLE
Confusion about the gazeto3d function

### ISSUE THREAD

**Issue by jinhong-ni** [Ahmednull/L2CS-Net#4]
Hi there,

Thanks for sharing your amazing work. I'm a bit confused about the output format of the model and how gazeto3d function works. Could you please give some intuitions about what the input 'gaze' and the output 'gaze_gt' refer to? Much appreciated!

**Comment by Ahmednull** [comment]
The most common practice to measure the gaze estimation accuracy/error is in terms of angular error. The angular error is measured between the actual gaze direction ($g ∈ R^3 $) and predicted gaze direction (ˆg ∈ R3) defined as

**Comment by Ahmednull** [comment]
The output of the model is the gaze direction in spherical angles (pitch and yaw). The angular error is measured between the actual gaze direction (<img src="https://latex.codecogs.com/svg.image?\mathrm{g}&space;\epsilon&space;\mathbb{R}^{3}" title="https://latex.codecogs.com/svg.image?\mathrm{g} \epsilon \mathbb{R}^{3}" />) and predicted gaze direction (<img src="https://latex.codecogs.com/svg.image?\mathrm{\hat{g}&space;\epsilon&space;\mathbb{R}^{3}" title="https://latex.codecogs.com/svg.image?\mathrm{\hat{g} \epsilon \mathbb{R}^{3}" />) defined as:
<img src="https://latex.codecogs.com/svg.image?\mathcal{L}_{angular}&space;=&space;\frac{\mathrm{g}\cdot&space;\mathrm{\hat{g}}}{\left&space;\|\mathrm{g}\right&space;\|&space;&space;\left&space;\|&space;\mathrm{\hat{g}}&space;\right&space;\|}" title="https://latex.codecogs.com/svg.image?\mathcal{L}_{angular} = \frac{\mathrm{g}\cdot \mathrm{\hat{g}}}{\left \|\mathrm{g}\right \| \left \| \mathrm{\hat{g}} \right \|}" />. 

So, gazeto3d method used to convert the gaze pitch yaw angles into 3D vector to calculate the angular error.
