### ISSUE TITLE
More bins MPII Face Gaze

### ISSUE THREAD

**Issue by janglinko-dac** [Ahmednull/L2CS-Net#8]
Hey, 
at first, thank You for great work and sharing results.

I have a question about number of bins. Has this number been tuned in trial-and-error process? Can I increase the number of bins to improve performance, or 28 is optimal number?

If change the number of bins, how i should change the equation used to map bins to degrees? https://github.com/Ahmednull/L2CS-Net/issues/3

Best,
Jan

**Comment by Ahmednull** [comment]
You can use this equation to tune the number of bins:

<img src="https://latex.codecogs.com/svg.image?&space;\theta_{p}&space;=w&space;\sum_{i=1}^b&space;p_i&space;(i-&space;&space;\frac{1&plus;b}{2})" title="https://latex.codecogs.com/svg.image? \theta_{p} =w \sum_{i=1}^b p_i (i- \frac{1+b}{2})" />


where $\theta_{p}$ is the predicted gaze angle, $p_i$ is the probability of the $i'th$ bin, $w$ is the bin width in degrees and $b$ is the number of bins
