### ISSUE TITLE
demo.py yaw and pitch 

### ISSUE THREAD

**Issue by enzoturletti** [Ahmednull/L2CS-Net#9]
Hello, I need to convert yaw and pitch to target in the screen. It is possible with this demo? Any suggestion is welcome

**Comment by Ahmednull** [comment]
We already did this in the demo.py file using draw_gaze() method at this line 
(https://github.com/Ahmednull/L2CS-Net/blob/9c36383deba3322c6c4742fce4d936f4412f8a97/demo.py#L151)

It takes the gaze angles pitch and yaw and convert them into pixel location in the screen.
